@include("html-header")
@include("nav")
@include("header")
<input type="hidden" id="ri" value="no">
@include("slider")
@include("services")
@include("client")
@include("logos")
@include("team")
@include("contact")
@include("footer")
@include("html-footer")